%%%----------------------------------------------------------------------
%%% File    : auto.hrl
%%% Author  : Alexander Tsvyashchenko <ejabberd@ndl.kiev.ua>
%%% Purpose : mod_archive2 automatic archiving regression testing expected
%%            replies
%%% Created : 05 Oct 2009 by Alexander Tsvyashchenko <ejabberd@ndl.kiev.ua>
%%%
%%% mod_archive2, Copyright (C) 2009 Alexander Tsvyashchenko
%%%
%%% This program is free software; you can redistribute it and/or
%%% modify it under the terms of the GNU General Public License as
%%% published by the Free Software Foundation; either version 2 of the
%%% License, or (at your option) any later version.
%%%
%%% This program is distributed in the hope that it will be useful,
%%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%%% General Public License for more details.
%%%
%%% You should have received a copy of the GNU General Public License
%%% along with this program; if not, write to the Free Software
%%% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
%%% 02111-1307 USA
%%%
%%%----------------------------------------------------------------------

-define(AUTO_TC1_RETRIEVE_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,
        ?NS,
        [{?NS,
          none}],
        list,[],
        [{xmlel,
          ?NS,[],
          chat,
          [{xmlattr,undefined,with,<<?CLIENTJID2>> = With},
           {xmlattr,undefined,start,
            Start}],
          []},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"1">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT2,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,'jabber:client',[],chat,
        [{xmlattr,undefined,with,<<?CLIENTJID2>>},
         {xmlattr,undefined,start,
          _},
         {xmlattr,undefined,subject,<<"Test">>}],
        [{xmlel,'jabber:client',[],to,
          [{xmlattr,undefined,secs,_}],
          [{xmlel,'jabber:client',[],body,[],
            [{xmlcdata,<<"This is test message.">>}]}]},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"1">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT3,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,
        ?NS,
        [{?NS,
          none}],
        list,[],
        [{xmlel,
          ?NS,[],
          chat,
          [{xmlattr,undefined,with,
            <<?CLIENTJID2 "/", _/binary>> = With3},
           {xmlattr,undefined,start,
            Start3}],
          []},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"1">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT4,
   {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,'jabber:client',[],chat,
        [{xmlattr,undefined,with,
          <<?CLIENTJID2 "/", _/binary>>},
         {xmlattr,undefined,start,
          _},
         {xmlattr,undefined,subject,<<"Test2">>}],
        [{xmlel,'jabber:client',[],to,
          [{xmlattr,undefined,secs,_}],
          [{xmlel,'jabber:client',[],body,[],
            [{xmlcdata,<<"This is test message.">>}]}]},
         {xmlel,'jabber:client',[],from,
          [{xmlattr,undefined,secs,_}],
          [{xmlel,'jabber:client',[],body,[],
            [{xmlcdata,<<"This is test message reply.">>}]}]},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"2">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT5,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,
        ?NS,
        [{?NS,
          none}],
        list,[],
        [{xmlel,
          ?NS,[],
          chat,
          [{xmlattr,undefined,with,
            <<?CLIENTJID2 "/", _/binary>>},
           {xmlattr,undefined,start,
            _}],
          []},
         {xmlel,
          ?NS,[],
          chat,
          [{xmlattr,undefined,with,
            <<?CLIENTJID2>> = With5},
           {xmlattr,undefined,start,
            Start5}],
          []},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"2">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT6,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,'jabber:client',[],chat,
        [{xmlattr,undefined,with,<<?CLIENTJID2>>},
         {xmlattr,undefined,start,
          _},
         {xmlattr,undefined,subject,<<"Test">>},
         {xmlattr,undefined,thread,<<"thread-12345">>}],
        [{xmlel,'jabber:client',[],to,
          [{xmlattr,undefined,secs,_}],
          [{xmlel,'jabber:client',[],body,[],
            [{xmlcdata,<<"This is test message 2.">>}]}]},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"1">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT7,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,
        ?NS,
        [{?NS,
          none}],
        list,[],
        [{xmlel,
          ?NS,[],
          chat,
          [{xmlattr,undefined,with,
            <<?CLIENTJID2 "/", _/binary>>},
           {xmlattr,undefined,start,
            _}],
          []},
         {xmlel,
          ?NS,[],
          chat,
          [{xmlattr,undefined,with,
            <<?CLIENTJID2 "/", _/binary>> = With7},
           {xmlattr,undefined,start,
            Start7}],
          []},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"2">>}]}]}]}]}}).

-define(AUTO_TC1_RETRIEVE_RESULT8,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,undefined,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,from,<<?CLIENTJID>>},
       {xmlattr,undefined,to,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,id,<<"stanza-",_/binary>>},
       {xmlattr,undefined,type,<<"result">>}],
      [{xmlel,'jabber:client',[],chat,
        [{xmlattr,undefined,with,
          <<?CLIENTJID2 "/", _/binary>>},
         {xmlattr,undefined,start,
          _},
         {xmlattr,undefined,subject,<<"Test2">>},
         {xmlattr,undefined,thread,<<"thread-12345">>}],
        [{xmlel,'jabber:client',[],to,
          [{xmlattr,undefined,secs,_}],
          [{xmlel,'jabber:client',[],body,[],
            [{xmlcdata,<<"This is test message 2.">>}]}]},
         {xmlel,'jabber:client',[],from,
          [{xmlattr,undefined,secs,_}],
          [{xmlel,'jabber:client',[],body,[],
            [{xmlcdata,<<"This is test message reply 2.">>}]}]},
         {xmlel,'http://jabber.org/protocol/rsm',
          [{'http://jabber.org/protocol/rsm',none}],
          set,[],
          [{xmlel,'http://jabber.org/protocol/rsm',[],first,
            [{xmlattr,undefined,index,<<"0">>}],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],last,[],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],changed,
            [],
            [{xmlcdata,_}]},
           {xmlel,'http://jabber.org/protocol/rsm',[],count,[],
            [{xmlcdata,<<"2">>}]}]}]}]}}).
