%%%----------------------------------------------------------------------
%%% File    : manual.hrl
%%% Author  : Alexander Tsvyashchenko <xmpp@endl.ch>
%%% Purpose : mod_archive2 manual archiving regression testing expected replies
%%% Created : 27 Sep 2009 by Alexander Tsvyashchenko <xmpp@endl.ch>
%%%
%%% mod_archive2, Copyright (C) 2009 Alexander Tsvyashchenko
%%%
%%% This program is free software; you can redistribute it and/or
%%% modify it under the terms of the GNU General Public License as
%%% published by the Free Software Foundation; either version 2 of the
%%% License, or (at your option) any later version.
%%%
%%% This program is distributed in the hope that it will be useful,
%%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%%% General Public License for more details.
%%%
%%% You should have received a copy of the GNU General Public License
%%% along with this program; if not, write to the Free Software
%%% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
%%% 02111-1307 USA
%%%
%%%----------------------------------------------------------------------

-define(MANUAL_TC1_UPLOAD_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"juliet@capulet.com/chamber">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T02:56:15.000000Z">>},
           {xmlattr,undefined,<<"subject">>,<<"She speaks!">>},
           {xmlattr,undefined,<<"thread">>,<<"damduoeg08">>},
           {xmlattr,undefined,<<"version">>,<<"0">>}],
          []}]}]}}).

-define(MANUAL_TC1_UPLOADED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"juliet@capulet.com/chamber">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T02:56:15.000000Z">>},
           {xmlattr,undefined,<<"subject">>,<<"She speaks!">>},
           {xmlattr,undefined,<<"thread">>,<<"damduoeg08">>},
           {xmlattr,undefined,<<"version">>,<<"0">>}],
          [{xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"0">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"Art thou not Romeo, and a Montague?">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"1">>}]}]}]}]}}).

-define(MANUAL_TC2_CHANGE_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"juliet@capulet.com/chamber">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T02:56:15.000000Z">>},
           {xmlattr,undefined,<<"subject">>,<<"She speaks twice!">>},
           {xmlattr,undefined,<<"version">>,<<"1">>}],
          []}]}]}}).

-define(MANUAL_TC2_CHANGED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"juliet@capulet.com/chamber">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T02:56:15.000000Z">>},
           {xmlattr,undefined,<<"subject">>,<<"She speaks twice!">>},
           {xmlattr,undefined,<<"thread">>,<<"damduoeg08">>},
           {xmlattr,undefined,<<"version">>,<<"1">>}],
          [{xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"0">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"Art thou not Romeo, and a Montague?">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"1">>}]}]}]}]}}).

-define(MANUAL_TC3_CHANGE_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"juliet@capulet.com/chamber">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T02:56:15.000000Z">>},
           {xmlattr,undefined,<<"subject">>,<<"She speaks!">>},
           {xmlattr,undefined,<<"version">>,<<"2">>}],
          []}]}]}}).

-define(MANUAL_TC3_CHANGED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"juliet@capulet.com/chamber">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T02:56:15.000000Z">>},
           {xmlattr,undefined,<<"subject">>,<<"She speaks!">>},
           {xmlattr,undefined,<<"thread">>,<<"damduoeg08">>},
           {xmlattr,undefined,<<"version">>,<<"2">>}],
          [{xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"utc">>,
              <<"1469-07-21T00:32:29.000000Z">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"Art thou not Romeo, and a Montague?">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"0">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"Art thou not Romeo, and a Montague?">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"7">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"How cam">>},
               {xmlcdata,<<"'">>},
               {xmlcdata,
                <<"st thou hither, tell me, and wherefore?">>}]}]},
           {xmlel,'urn:xmpp:archive',[],to,
            [{xmlattr,undefined,<<"secs">>,<<"11">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"Neither, fair saint, if either thee dislike.">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"4">>}]}]}]}]}}).

-define(MANUAL_TC4_UPLOAD_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"balcony@house.capulet.com">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:16:37.000000Z">>},
           {xmlattr,undefined,<<"version">>,<<"0">>}],
          []}]}]}}).

-define(MANUAL_TC4_UPLOADED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"balcony@house.capulet.com">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:16:37.000000Z">>},
           {xmlattr,undefined,<<"version">>,<<"0">>}],
          [{xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"0">>},
             {xmlattr,undefined,<<"name">>,<<"benvolio">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"She will invite him to some supper.">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"3">>},
             {xmlattr,undefined,<<"name">>,<<"romeo">>},
             {xmlattr,undefined,<<"jid">>,<<"romeo@montague.net">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"What hast thou found?">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"6">>},
             {xmlattr,undefined,<<"name">>,<<"mercutio">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"A bawd, a bawd, a bawd! So ho!">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"3">>}]}]}]}]}}).

-define(MANUAL_TC5_UPLOAD_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,<<"benvolio@montague.net">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:01:54.012340Z">>},
           {xmlattr,undefined,<<"version">>,<<"0">>}],
          [{xmlel,'urn:xmpp:archive',[],next,
            [{xmlattr,undefined,<<"with">>,
              <<"balcony@house.capulet.com">>},
             {xmlattr,undefined,<<"start">>,
              <<"1469-07-21T03:16:37.000000Z">>}],
            []}]}]}]}}).

-define(MANUAL_TC5_UPLOADED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,<<"benvolio@montague.net">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:01:54.012340Z">>},
           {xmlattr,undefined,<<"version">>,<<"0">>}],
          [{xmlel,'urn:xmpp:archive',[],next,
            [{xmlattr,undefined,<<"with">>,
              <<"balcony@house.capulet.com">>},
             {xmlattr,undefined,<<"start">>,
              <<"1469-07-21T03:16:37.000000Z">>}],
            []},
           {xmlel,'urn:xmpp:archive',[],to,
            [{xmlattr,undefined,<<"secs">>,<<"0">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"O, I am fortune">>},
               {xmlcdata,<<"'">>},
               {xmlcdata,<<"s fool!">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"4">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"Why dost thou stay?">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"2">>}]}]}]}]}}).

-define(MANUAL_TC5_CHANGE_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"balcony@house.capulet.com">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:16:37.000000Z">>},
           {xmlattr,undefined,<<"version">>,<<"1">>}],
          [{xmlel,'urn:xmpp:archive',[],previous,
            [{xmlattr,undefined,<<"with">>,
              <<"benvolio@montague.net">>},
             {xmlattr,undefined,<<"start">>,
              <<"1469-07-21T03:01:54.012340Z">>}],
            []}]}]}]}}).

-define(MANUAL_TC5_CHANGED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"balcony@house.capulet.com">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:16:37.000000Z">>},
           {xmlattr,undefined,<<"version">>,<<"1">>}],
          [{xmlel,'urn:xmpp:archive',[],previous,
            [{xmlattr,undefined,<<"with">>,
              <<"benvolio@montague.net">>},
             {xmlattr,undefined,<<"start">>,
              <<"1469-07-21T03:01:54.012340Z">>}],
            []},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"0">>},
             {xmlattr,undefined,<<"name">>,<<"benvolio">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"She will invite him to some supper.">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"3">>},
             {xmlattr,undefined,<<"name">>,<<"romeo">>},
             {xmlattr,undefined,<<"jid">>,<<"romeo@montague.net">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"What hast thou found?">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"6">>},
             {xmlattr,undefined,<<"name">>,<<"mercutio">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"A bawd, a bawd, a bawd! So ho!">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"3">>}]}]}]}]}}).

-define(MANUAL_TC6_CHANGE_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"balcony@house.capulet.com">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:16:37.000000Z">>},
           {xmlattr,undefined,<<"version">>,<<"2">>}],
          []}]}]}}).

-define(MANUAL_TC6_CHANGED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,
            <<"balcony@house.capulet.com">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:16:37.000000Z">>},
           {xmlattr,undefined,<<"version">>,<<"2">>}],
          [{xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"0">>},
             {xmlattr,undefined,<<"name">>,<<"benvolio">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"She will invite him to some supper.">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"3">>},
             {xmlattr,undefined,<<"name">>,<<"romeo">>},
             {xmlattr,undefined,<<"jid">>,<<"romeo@montague.net">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"What hast thou found?">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"6">>},
             {xmlattr,undefined,<<"name">>,<<"mercutio">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,
                <<"A bawd, a bawd, a bawd! So ho!">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"3">>}]}]}]}]}}).

-define(MANUAL_TC7_CHANGE_RESULT,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
      [{xmlel,?NS_ARCHIVING,
        [{?NS_ARCHIVING,none}],
        save,[],
        [{xmlel,'urn:xmpp:archive',[],chat,
          [{xmlattr,undefined,<<"with">>,<<"benvolio@montague.net">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:01:54.012340Z">>},
           {xmlattr,undefined,<<"version">>,<<"1">>}],
          [{xmlel,'jabber:x:data',
            [{'jabber:x:data',none}],
            x,
            [{xmlattr,undefined,<<"type">>,<<"submit">>}],
            [{xmlel,'jabber:x:data',[],field,
              [{xmlattr,undefined,<<"var">>,<<"FORM_TYPE">>}],
              [{xmlel,'jabber:x:data',[],value,[],
                [{xmlcdata,
                  <<"http://example.com/archiving">>}]}]}]}]}]}]}}).

-define(MANUAL_TC7_CHANGED,
    {received_packet,iq,"result",
     {<<?CLIENTNAME>>,<<?SERVERHOST>>,undefined},
     "stanza-" ++ _,?NS_ARCHIVING,
     {xmlel,'jabber:client',[],iq,
      [{xmlattr,undefined,<<"from">>,<<?CLIENTJID>>},
       {xmlattr,undefined,<<"to">>,
        <<?CLIENTJID "/", _/binary>>},
       {xmlattr,undefined,<<"id">>,<<"stanza-",_/binary>>},
       {xmlattr,undefined,<<"type">>,<<"result">>}],
        [{xmlel,?NS_ARCHIVING,[{?NS_ARCHIVING, none}],chat,
          [{xmlattr,undefined,<<"with">>,<<"benvolio@montague.net">>},
           {xmlattr,undefined,<<"start">>,
            <<"1469-07-21T03:01:54.012340Z">>},
           {xmlattr,undefined,<<"version">>,<<"1">>}],
          [{xmlel,'urn:xmpp:archive',[],next,
            [{xmlattr,undefined,<<"with">>,
              <<"balcony@house.capulet.com">>},
             {xmlattr,undefined,<<"start">>,
              <<"1469-07-21T03:16:37.000000Z">>}],
            []},
           {xmlel,'jabber:x:data',
            [{'jabber:x:data',none}],
            x,
            [{xmlattr,undefined,<<"type">>,<<"submit">>}],
            [{xmlel,'jabber:x:data',[],field,
              [{xmlattr,undefined,<<"var">>,<<"FORM_TYPE">>}],
              [{xmlel,'jabber:x:data',[],value,[],
                [{xmlcdata,
                  <<"http://example.com/archiving">>}]}]}]},
           {xmlel,'urn:xmpp:archive',[],to,
            [{xmlattr,undefined,<<"secs">>,<<"0">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"O, I am fortune">>},
               {xmlcdata,<<"'">>},
               {xmlcdata,<<"s fool!">>}]}]},
           {xmlel,'urn:xmpp:archive',[],from,
            [{xmlattr,undefined,<<"secs">>,<<"4">>}],
            [{xmlel,'urn:xmpp:archive',[],body,[],
              [{xmlcdata,<<"Why dost thou stay?">>}]}]},
           {xmlel,'http://jabber.org/protocol/rsm',
            [{'http://jabber.org/protocol/rsm',none}],
            set,[],
            [{xmlel,'http://jabber.org/protocol/rsm',[],first,
              [{xmlattr,undefined,<<"index">>,<<"0">>}],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],last,
              [],
              [{xmlcdata,_}]},
             {xmlel,'http://jabber.org/protocol/rsm',[],count,
              [],
              [{xmlcdata,<<"2">>}]}]}]}]}}).
